services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && 
              gunicorn --workers 3 --bind 0.0.0.0:8000 django_project.wsgi:application"
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network

volumes:
  static_volume:

networks:
  app-network:
    name: app-network
    driver: bridge
